### PR TITLE
Added ability to overwrite Object SID when forging Golden Certificate…

### PR DESCRIPTION
**Pull request by RazzburyPi**
…s to bypass szOID_NTDS_CA_SECURITY_EXT checks

### CODE REVIEW

**Comment by ly4k** [comment]
Hello @RazzburyPi This is a great addition, thank you! I am however unsure of the prefix you add. Have you tested with different length of SIDs? I'd prefer if this prefix was an ASN1 structure object rather than a hard coded string to make it more clear. If you don't have much experience with ASN1, you can use an online decoder and look at some of my ASN1 structure objects. Otherwise, I'll see if I can make it for you 🙂

**Comment by RazzburyPi** [comment]
@ly4k The prefix is something I identified by simply hexdumping the existing value for that extension from a valid certificate, and then finding a way to "make it work" when modifying that attribute. So far this change has been successful in two different environments. I do not have any experience with ASN1 objects, but am looking into incorporate a more "proper" solution, once I figure out how to properly modify the extension with an ASN1 object, I will update my repo and submit another PR. Thanks for your help!

**Comment by RazzburyPi** [comment]
@ly4k Implemented ASN1 structure when building the security extension as you requested, also added ability to provide extension when requesting certificate as well to maintain ESC1 functionality post-certificate authentication patching.

**Comment by ly4k** [comment]
Added in latest release. Thank you though!

**Pull request closed without merging**
